---
title: "Alternative visualizations"
author: Anton Antonov
date: 2020-04-14
output: html_notebook
---

```{r}
library(hexbin)
```

# Geo-histogram (2020-04-14)

## ggplot2

Not that these are just location denisities:

```{r}
ggplot( dsNYDataCountiesExtended[, c("Lat", "Lon", "Cases")] ) +
  geom_hex( aes( x = Lon, y = Lat ) )
```

## hexbin

This would have been nice if worked with less obscure workflow/option settings:

```{r}
hb2 <- hexbin::hexbin( x = dsNYDataCountiesExtended$Lon, y = dsNYDataCountiesExtended$Lat, xbins = 20, xlab = "Longitude", ylab = "Latitude" )
P <- plot(hb2, type="n", main = "Cases" )
hexbin::pushHexport(P$plot.vp)
hexbin::grid.hexagons(hb2, style= "nested.centroids", mincnt = 2, use.count = FALSE, cell.at = dsNYDataCountiesExtended$Cases )
grid::popViewport()
```


# Highchart (2020-05-27)

(That library usage is not free for commercial and governmental usage.)

```{r}
mapdata <- get_data_from_map(download_map_data("https://code.highcharts.com/mapdata/countries/us/us-all-all.js"))
Summary(mapdata)
```


```{r}
dsNYDataCountiesExtended
```

```{r}
highcharter::hcmap("countries/us/us-all-all", 
      data = dsNYDataCountiesExtended,
      name = "Cases", value = "Cases", 
      joinBy = c("fips", "Fips"),
      borderColor = "transparent") %>%
  highcharter::hc_colorAxis(dataClasses = highcharter::color_classes( quantile(dsNYDataCountiesExtended$Cases, seq(0,1,0.1)) ) ) %>% 
  highcharter::hc_legend(layout = "vertical", align = "right",
                         floating = TRUE, valueDecimals = 0, valueSuffix = "") 
```